// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://kdyultegduvfggjovban.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeXVsdGVnZHV2Zmdnam92YmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxNzU0MTgsImV4cCI6MjA0Nzc1MTQxOH0.DwQWUkQPAAekv-cC9hNgT8_0Ut_DJHafN9dEH8Hu-Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);