name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --base=/hebammenwartgeld-kanton-zug/
        env:
          PUBLIC_URL: '/hebammenwartgeld-kanton-zug'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  # Changed to the correct version
        with:
          path: ./dist  # Ensure that `./dist` is the correct build output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1  # Ensure version consistency
